sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: Wj2ISMyf6jXi3Kem2I+9dlaKihQAud3McAwTc8RnGAnHjSZLr2gkT3v4xDlZrWEmXj4v5cQBJz/lcstYtzyKoghEU+15p+GZExv9r9+bUDnPxeGHGqr1r8op1HB3XC+soNrq1l5QarDLDr6uITzhDVxGaoxk7ilxZkotTBwke2+4qRyOCek7gjz07kCDODqKOT6nFcO/rJc5B9h2oJ7Ubqjg5DbrUu0GOyr7Z7IZ6jhL4T/Ph5T6VxQpNPpLoAakH9NHX/4yK+Sl7qsBsdeBdn/wSl6evvBZNwBVP38y7PITZ3i3GbSk30x3u5UiK/p+FmxZ8N6zuSFS1bwAa7zqw1594UtPNLOPqq3LvlSLkyQ7X/l7qswBJCR9OqOKb47cORCSAbszEFDFtZbMWFutWKNZfa4Cy4ZjpTPCYAOvxievuLUBCPJ+zfSv34MlxUiBuKsqxJdQ2y+dP9MTAuhmeLSY6MTDoUCNwxTEBoVR8q+1ffuMEGVyg9dNznfAir06OVLZLNb6VaOYXg0aYqwnayyuRdK1E+bWU+K1Hzt7+cxV/7GCrt6B+yYtv0iDBXzc/sH51u57kxEL6bDItez7MJGqq0Jf56IAUQfhqbNIkC3+jK6BpUmkudt84tqMTrq2smQ70GVhxlJdZtgGdbncYxlv7u5z9kTA21Q45k8LtKQ=
  - secure: kR/dELD3baOjZG03lIdUlNKXnYXAxv2f1SMSGRpPrqFLrXR6Pia7z6rGlVCJOF2Mz7eyKlFHYUQWCqCznyv377M1ofCVOpGVG0aUTKH43YhAh1ceFW6Fd5ZlUO86uB4Ui2Tc2ObD8sNQOct9OBQhRqD7R/bGFD99IxKtPU65Y/St5qNEnCUAgxgwsF5kGQL/tVYoK4VVysrkHTYE0+wd/k5ZkHb2TduK5yRQmhHO1GK51hBjDE8I3Qi2OkvVOAaBXCPv3Kf4j1Yqzrph5s6FzQsnn1fmahjUd4/u+GUUcmKKNSL1wOKh4if7OeMoiIZJlBntLNsAs0xSQfjIHlwKaMDSM3G5ckqW7Vd6qgHBtBALEGgyXW5QW4XxznTfIjCfl5EUlVJGnMHPu1e7k+zu/eErdGLuQGH0qQSSsg8pZItpCy7d1f7fE+QPvjGIx6FqR2jKokyRTBkWKyTYQdyFjMfz6RrOZkHpn5k1Upj4SoJZpyNPyEWP/56WEG+Qi3KjRWGs6rFFsJ6gP2VMYYRAR0W9q2NDHkuWGwKtk01FKAYxbc8w9EAtvJe6xbHJaynxKbhA8NfF+hTXxcYlkzvDNUTyCovh2v2whW9+BJ58Y/MRNmclYrk3EMdPyXX6g48jYGISnPi0X3Sku79Xg9S8TSej43Q4qN0BT0GW0J0PZtA=
